apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig.yaml

resources:
# - ../../base
- ../../webhook

images:
- name: docker.io/ofekmeister/csi-gcs
  newTag: dev
- name: csi-gcs-webhook-server
  newTag: dev

namespace: kube-system

patchesStrategicMerge:
#- uselocalimage.yaml
- webhook-uselocalimage.yaml
- webhook-cert-server.yaml
- webhook-cert-client.yaml

# requires the run 'invoke tls-cert'
secretGenerator:
  - name: csi-gcs-webhook
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
      - ca=secrets/tls.crt
    type: "kubernetes.io/tls"

vars:
  - name: WEBHOOK_CA_BUNDLE
    objref:
      apiVersion: v1
      kind: Secret
      name: csi-gcs-webhook
    fieldref:
      fieldpath: data.ca # should be possible to do data[tls.crt] but doesn't seem to work with kustomize/v4.1.2