apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-gcs-webhook-server
spec:
  template:
    spec:
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: csi-gcs-webhook
      containers:
        - name: server
          volumeMounts:
              - mountPath: /tls
                name: cert
                readOnly: true